### ISSUE TITLE
New CF Challenge : __cf_chl_jschl_tk__ (PHP form)

### ISSUE THREAD

**Issue by LaneSh4d0w** [RyuzakiH/CloudflareSolverRe#14]
This is the brand new CF challenge, that some websites adopted. Basically, at the end of the CF DDoS website, you have a form that the browser sends to the website, which verifies your access, and then permits you to access the website.

**Comment by ngosang** [comment]
@RyuzakiH I confirm this issue. Is happening in this site => https://extratorrent.si

**Comment by ngosang** [comment]
I have found:
* https://github.com/scaredos/cfresearch#js-challenge-new
* https://github.com/VeNoMouS/cloudscraper/search?q=__cf_chl_jschl_tk__&unscoped_q=__cf_chl_jschl_tk__

**Comment by RyuaNerin** [comment]
I have found something seems like useful for this problem.

- https://github.com/Seuntjie900/DiceBot/blob/019de170148de36841fc961d9fcab6820107cd60/DiceBot/Cloudflare.cs
