### ISSUE TITLE
False positive with Captcha too

### ISSUE THREAD

**Issue by Mandrakia** [RyuzakiH/CloudflareSolverRe#2]
I think the same false positive is present with captcha.

result.IsSuccess is true (method captcha) but no cf_clearance cookie and next call just results in a 503.

**Comment by RyuzakiH** [comment]
Does it happen in the latest version?
I updated the success condition in js & captcha solvers, last issue.
Can you give me the website and the code to reproduce that false positive?
Or use Fiddler and show me the last two sessions (the solution submit, the next call that results in 503).

**Comment by Mandrakia** [comment]
Oh it wasn't in 1.03 Lemme check !

**Comment by RyuzakiH** [comment]
Still not working?

**Comment by Mandrakia** [comment]
It is working as intended ! I'm having other issues now but unrelated thanks :)

**Comment by RyuzakiH** [comment]
Good, you're welcome.
Feel free to report any issue that faces you, it helps a lot.
