### ISSUE TITLE
i think cloudflare change their code again

### ISSUE THREAD

**Issue by longcharmroeun** [RyuzakiH/CloudflareSolverRe#22]
var target = "https://kissasian.sh/";

                    var useragen = "Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1";

                    var cf = new CloudflareSolver(useragen)
                    {
                        MaxTries = 3,
                        ClearanceDelay = 3000
                    };

                    var handler = new HttpClientHandler();
                    var client = new HttpClient(handler);

                    var result1 = await cf.Solve(new Uri(target), useragen);

                    Console.WriteLine(result1.FailReason);

i got Unknown protection detected

**Comment by Artarex** [comment]
Yep. Get the same error message. (On a different website)

The website says: "Please turn on javascript...."
So it seems like the javascript bypass is not working anymore?

**Comment by longcharmroeun** [comment]
i have been change your code: 
``private static readonly Regex JsChallengeRegex = new Regex(@"<script.*?>(?<script>.*?var s,t,o,p, b,r,e,a,k,i,n,g,f, (?<className>\w+?)={""(?<propName>\w+?)"":(?<propValue>.*?)};.*?(?<calculations>\s*?\w+?\.\w+?[+\-*\/]=(?:(?<normal>(?:\+|\(|\)|\!|\[|\]|\/)+?;)|(?<charCode>(?:\+|\(|\)|\!|\[|\]|\/)+?\(function.*?}\(.*?\)\)\);)|(?<cfdn>function\(.\)\{var.*?;\s.*?;)))+.*?a\.value\s=\s\(\+\w+\.\w+(\s\+\s(?<addHostLength>t\.length))*?\)\.toFixed\((?<round>\d+)\);.*?},\s*(?<delay>\d+)\);.*?)<\/script>.*?<form.+?action=""(?<action>\S+?)"".*?>.*?name=""r"" value=""(?<r>\S+)"".*?value=""(?<jschl_vc>[a-z0-9]{32})"".*?id=""jschl-vc"".*?name=""pass"" value=""(?<pass>\S+?)"".*?</form>.*?(id=""cf-dn-\S+"">(?<cf_dn>.*?)</div>\s+<div.*?){0,1}\s+</div>", RegexOptions.Singleline/* | RegexOptions.Compiled*/);

everything is the same as original GET and POST https://kissasian.sh/
but it keep redirect. 

![Progress Telerik Fiddler Web Debugger 4_22_2020 6_50_10 PM](https://user-images.githubusercontent.com/42161560/79978772-a5508800-84ca-11ea-9dc9-18f1f2155583.png)

**Comment by longcharmroeun** [comment]
finally it working now i will summit my code to you.

**Comment by Artarex** [comment]
My website is website for example Does your new code works their too? Would be awesome if you could check this :)

**Comment by longcharmroeun** [comment]
i need to change a lot of code to keep it multithreading but it take long time
or just use my class for temporarily ?

**Comment by longcharmroeun** [comment]
https://github.com/longcharmroeun/TemporaryWebclient

my code that working

**Comment by Artarex** [comment]
I tried to use it in a programm called openbullet (Which is multithreaded) 
But for my website I still get the same error message with openbullet 
(Unknown protection, skipping the bypass!)

Could you do me maybe a favour? 
Could you maybe compile me the CloudflareSolverRe.dll please? (Without the TemporaryWebclient)
To keep it multithreaded, follow the last comment in this issue: https://github.com/RyuzakiH/CloudflareSolverRe/issues/15 (It is just removing / commenting out 2-3 things)

Maybe I did a stupid mistake when I compiled it or forgot something. I simply can't get it to work.
Thanks alot!

**Comment by longcharmroeun** [comment]
@Artarex i don't know but
I will try to testing you websites

**Comment by Artarex** [comment]
> 
> 
> @Artarex i don't know but
> I will try to testing you websites

Thanks! Test it on webiste.com

I compiled your code right now again and used the .dll on openbullet but it still gives unknown protection.
Would be awesome if you find out on my website what causes the problem.
Thanks alot :)

**Comment by longcharmroeun** [comment]
https://github.com/longcharmroeun/TemporaryWebclient
already fix your website is working now

**Comment by Artarex** [comment]
Yes it is working now. Thank you!

**Comment by ngosang** [comment]
Another fix in #24 
Binary => https://www.nuget.org/packages/CloudflareSolverReNgosang/1.0.6.2
