### ISSUE TITLE
Javascript regex update

### ISSUE THREAD

**Issue by nebojsasandin** [RyuzakiH/CloudflareSolverRe#26]
Cloudflare was updated recently, and the:
`CloudflareSolverRe.Types.Javascript.JsChallenge.JsChallengeRegex`
...needs an update.

I'm using this one:
`private static readonly Regex JsChallengeRegexS = new Regex(@"(?<script>.*?var s,t,o,p, b,r,e,a,k,i,n,g,\w, (?<className>\w+?)={""(?<propName>\w+?)"":(?<propValue>.*?)};[\w\W\s\S\n\r.]*?(?<calculations>\s*?\w+?\.\w+?[+\-*\/]=(?:(?<normal>(?:\+|\(|\)|\!|\[|\]|\/)+?;)|(?<charCode>(?:\+|\(|\)|\!|\[|\]|\/)+?\(function.*?}\(.*?\)\)\);)|(?<cfdn>function\(.\)\{var.*?;\s.*?;)))+.*?a\.value\s=\s\(\+\w+\.\w+\)\.toFixed\((?<round>\d+)\);.*?[\w\W\s\S\n\r.]*?},\s*(?<delay>\d+)\);.*?)([\w\W\s\S\n\r.]*?form.*action="")(?<action>\S+?)("")([\w\W\s\S\n\r.]*?name=""r""\svalue="")(?<r>\S+?)(""[\w\W\s\S\n\r.]*?value="")(?<jschl_vc>\w*)(""[\w\W\s\S\n\r.]*?name=""pass""\svalue="")(?<pass>\S+?)(""[\w\W\s\S\n\r.]*?cf-dn-\S+"">)(?<cf_dn>\S+?)(</div>)", RegexOptions.Singleline);`
...and it's working fine.

**Comment by iIIusi0n** [comment]
um... not working for me

**Comment by ngosang** [comment]
Fix available => https://github.com/RyuzakiH/CloudflareSolverRe/pull/29
