### ISSUE TITLE
New Challenge

### ISSUE THREAD

**Issue by nebojsasandin** [RyuzakiH/CloudflareSolverRe#27]
According to this:

[https://github.com/VeNoMouS/cloudscraper/issues/185](https://github.com/VeNoMouS/cloudscraper/issues/185)

there's a new CF Challenge presented. It might be more difficult solving this one, but if it ever gets solved, can we have the solution integrated here?

**Comment by PrinceOwen9466** [comment]
I have written a small C# script to illustrate this issue. It seems like CloudFlare is raising
 the bar a little.

```
#r "nuget: CloudflareSolverRe.Captcha, 1.0.6"
using CloudflareSolverRe;

Console.WriteLine("Hello world!");

var target = new Uri("https://haapi.ankama.com/json/Ankama/v2/Api/CreateApiKey");
var cf = new CloudflareSolver
{
	MaxTries = 3,
	ClearanceDelay = 3000
};
var result = await cf.Solve(target);

Console.WriteLine($"{result.Success}");
Console.WriteLine($"{result.FailReason}");
Console.WriteLine($"{result.DetectResult}");
```

![CloudflareSolverRe Script](https://user-images.githubusercontent.com/35764351/80508718-52fee380-8970-11ea-8b6c-34df3e80ea9b.PNG)

**Comment by openbullet** [comment]
Guys I think the owner of this repository is not supporting it anymore. There are other forks that are working so please use another fork in the meantime or make your own fork and apply one of the two PRs that are pending.

**Comment by PrinceOwen9466** [comment]
@openbullet You seem to have a fork yourself, do you have any clue on the issue?

**Comment by openbullet** [comment]
There are 2 pull requests pending that solve the issue, i merged one of them on my fork, you can use it in the meantime, I also solved an issue I opened myself https://github.com/RyuzakiH/CloudflareSolverRe/issues/15 and for which I never got a reply. I think this repo is dead for the time being

**Comment by openbullet** [comment]
Soon I will also integrate my custom library for captcha solving since Cloudflare is now using HCaptcha as well and this library doesn't recognize it

**Comment by PrinceOwen9466** [comment]
@openbullet Well thanks for the heads up, I'll check it out 👍. Once my hands get less full, I would love to help with that custom library. Until then, Best of luck!

**Comment by euangordon** [comment]
@openbullet Moved onto your fork and it is working a treat. 

The site I am scraping is not using Captcha, just the standard challenge. 

How about creating a new repo? Happy to try and help where possible! I am scraping 30+ sites, but only one has CloudFlare for now.

**Comment by openbullet** [comment]
@euangordon I was going to heavily change the library for a new project I am working on, so when the time comes I'll make a new repo, for now I'll just update the fork.

**Comment by ngosang** [comment]
Fix available => https://github.com/RyuzakiH/CloudflareSolverRe/pull/29
