### ISSUE TITLE
Did cloudflare update again? Error parsing JS challenge HTML

### ISSUE THREAD

**Issue by Artarex** [RyuzakiH/CloudflareSolverRe#30]
I am using the CloudFlareSolver in a program and today i get the message: "Error parsing JS challenge HTML"

It happens on every website i tried it. 
For example: https://kissasian.sh
Does anyone of you has the same problem?
I am right now not 100% sure if I simply destroyed some configs in my programm or if cloudflare updated again.

**Comment by eastsida** [comment]
Cloud update. Lol It was working litrerally 3 hours ago.

**Comment by longcharmroeun** [comment]
No my project working fine xd

**Comment by longcharmroeun** [comment]
> No my project working fine xd

@Artarex

**Comment by Artarex** [comment]
Yeah my timing was really bad. Everything worked fine. I restarted my windows root and suddenly it did not work anymore. Worst timing ever. Because of that, i was not sure if it was my problem or a cloudflare update xD
Good to know I am not alone. 
You also use the resolver in openbullet @eastsida ?

**Comment by eastsida** [comment]
> Yeah my timing was really bad. Everything worked fine. I restarted my windows root and suddenly it did not work anymore. Worst timing ever. Because of that, i was not sure if it was my problem or a cloudflare update xD
> Good to know I am not alone.
> You also use the resolver in openbullet @eastsida ?
No, i am fixing Leaf.Xnet library. Wrote 2 methods for cloudflare. First returnt httprequest instance that already pass cloud and all future request goes without cloud check. And method that returns (proxy,cf_clearance cookie and user-agent) in case if i will use other http client or even other programming language ( i can dump proxy,cf_clearance cookie and user-agent to text file for example and use them in php or python for example) and make any future requests without cloud check.

**Comment by tchirou** [comment]
With jackett, we now have this problem with torrentz.eu and yggtorrent.se

**Comment by longcharmroeun** [comment]
I was worng that my project is working fine.
I noticed that error happen 6 time in 24h 
On my errors log.
Did anyone got that error?

**Comment by eastsida** [comment]
Can someone rewrite from this project
https://github.com/VeNoMouS/cloudscraper/tree/dev
https://github.com/VeNoMouS/cloudscraper/commit/49c508bfbd6beaebfb2ea446cc12ffefced50699
https://github.com/VeNoMouS/cloudscraper/issues/216

Things identified so far
is_New_IUAM_Challenge() regex change (fixed)
IUAM_Challenge_Response() Cloudflare put in new fake "jschl_vc" input (fixed)
jsfuck challenge changed but only occurs sometimes (investigating)
To this project.

**Comment by longcharmroeun** [comment]
i found that cloudflare have been change a little of them code again by random.

**Comment by ngosang** [comment]
**Update: 2020/05/15 v1.0.7.2** fix new challenge

#29

**Comment by longcharmroeun** [comment]
already fix https://www.nuget.org/packages/TemporaryWebclient/1.0.1

**Comment by Artarex** [comment]
@ngosang 
I tried your fix and sometimes get this error: 
ERROR: GetInnerHtmlById not found! id: CvSLwLVkzt12

**Comment by longcharmroeun** [comment]
@Artarex  try my dll

**Comment by ngosang** [comment]
@Artarex give me the URL to test.

**Comment by Artarex** [comment]
@ngosang https://reevown.com
Sometimes its working. Like 50/50

@Longcharm Can't test yours yet, need to edit some things to make it work for .net standard 1.3 . Will wait for ngosang since its working quite good already :)

**Comment by ngosang** [comment]
@Artarex I can't make it fail.
Could you add a breakpoint here https://github.com/RyuzakiH/CloudflareSolverRe/pull/29/files#diff-3235a8aceeee5624582809f8a2bd416dR57 and save the `html` file when it fails?

**Comment by longcharmroeun** [comment]
-> dotnetstandar2.0
https://www.nuget.org/packages/TemporaryWebclient/1.0.3

**Comment by Artarex** [comment]
@ngosang I couldn't reproduce it either on a clean install of openbullet in their newest version. So maybe my installation of openbullet + this dll was a bit messy and a component was missing.
If will check now if it runs fine over a longer period of time. 
But for now everything looks awesome.
Once again big thanks @ngosang  and @longcharmroeun  :)
