### ISSUE TITLE
Not working simple JS challenge

### ISSUE THREAD

**Issue by booooohdan** [RyuzakiH/CloudflareSolverRe#35]
This URL protected by Cloudflare: https://warthunder.ru/ru/community/userinfo/?nick=Keofox
Using Xamarin.Android. In debug, my program stuck on this string: `var result = cf.Solve(target).Result;`. I waiting for 5 and 10 minutes and don't get the result. This is my code:

     private async Task ConnectToSiteAsync()
        {
            var target = new Uri("https://warthunder.ru/ru/community/userinfo/?nick=Keofox");

            var cf = new CloudflareSolver
            {
                MaxTries = 3,
                ClearanceDelay = 3000
            };

            var result = cf.Solve(target).Result;

            if (!result.Success)
            {
                Console.WriteLine($"[Failed] Details: {result.FailReason}");
                return;
            }

            var request = (HttpWebRequest)WebRequest.Create(target);
            request.Headers.Add(HttpRequestHeader.Cookie, result.Cookies.AsHeaderString());
            request.Headers.Add(HttpRequestHeader.UserAgent, result.UserAgent);

            var response = (HttpWebResponse)request.GetResponse();
            var content = new StreamReader(response.GetResponseStream()).ReadToEnd();
            Log.Debug("My result", content);
        }

Calling method in OnCreate like this: `ConnectToSiteAsync().Wait();`

**Comment by longcharmroeun** [comment]
@booooooogdan 
Sorry this library is not working any more due to Cloudflare release new anti bot system.
you can try this [https://github.com/Jackett/Jackett/issues/9029](url)

**Comment by booooohdan** [comment]
> @booooooogdan
> Sorry this library is not working any more due to Cloudflare release new anti bot system.
> you can try this [https://github.com/Jackett/Jackett/issues/9029](url)

Link is broken. "No results matched your search."

**Comment by longcharmroeun** [comment]
> > @booooooogdan
> > Sorry this library is not working any more due to Cloudflare release new anti bot system.
> > you can try this [https://github.com/Jackett/Jackett/issues/9029](url)
> 
> Link is broken. "No results matched your search."

Here new link: https://github.com/ngosang/FlareSolverr
