### ISSUE TITLE
use URL as provided not http

### ISSUE THREAD

**Issue by meinname** [RyuzakiH/CloudflareSolverRe#5]
Hi,
is it possible to provide the URL as provided and not try to use http?

Reason:
Even when I use the url http**s**://uam.hitmehard.fun/HIT CloudflareSolverRe tries to request via http.

But the rotating proxy service I use (not rotating on every request but after a few min or on fails) jumps to the next proxy on 503 internally and after a few tries it sends a "504 Gateway Timeout  - unable to find suitable sub-proxy"
And the proxy service doesn't want to change the product and told: just request via https then It won't happen - who uses http on Cloudflare anyway?

**Comment by meinname** [comment]
Nevermind - the service now announced to fix this on their side.

**Comment by RyuzakiH** [comment]
Good!
Even if I tried, I think I can't solve it my side.
The way that service works cannot deal with cloudflare protected sites.
Cloudflare by default responds by 503 on the first request.
> not rotating on every request but after a few min or on fails
"on fails" means that it will always change and can't be solved here.
If you need, I can let you determine if you require https or not.
I use http as challenges cannot be solved in https easily (I don't know why) and requires more tries.

**Comment by meinname** [comment]
If the fix on service side works, I think a "force https" switch is not needed.
But thnx for the offer ;)

**Comment by RyuzakiH** [comment]
You're welcome :)
